### ISSUE TITLE
Javadoc for Constructor for CustomLinkedUrgencyQueue does not align with the Oracle implementation.

### ISSUE THREAD

**Issue by CoryBorek** [cs1302uga/cs1302-urgency-queue#3]
The provided javadoc for CustomLinkedUrgencyQueue states to throw a NullPointerException if you provide a null reference to the Comparator<T> input.

When you try to give a Null input to the Oracle implementation (which I was doing in my test cases), it does not properly throw the provided exception.

**Comment by bjb211** [comment]
Thanks for pointing this out. We've resolved the issue.
